# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 23:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('bio', models.CharField(blank=True, max_length=2083)),
                ('access_level', models.CharField(blank=True, max_length=15)),
                ('location', models.CharField(blank=True, max_length=2083)),
                ('street_address', models.CharField(blank=True, max_length=2083)),
                ('website', models.CharField(blank=True, max_length=2083)),
                ('social_media', models.CharField(blank=True, max_length=2083)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
