# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_profile', '0001_tracker_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='trackerprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='trackerprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='trackerprofile',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackerprofile',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
