# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_device', '0003_auto_20161009_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
